name: Compile

# trigger the workflow manually
on: workflow_dispatch

jobs:

  draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_draft_release.outputs.id }}
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
    steps:
      - name: Get version from tag
        id: tag_name
        run: echo RELEASE_VERSION=$(date +"%Y%m%d.%H%M%S") >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Create draft release
        id: create_draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          body: ${{ steps.changelog_reader.outputs.changes }}
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
          asset_name: universalJavaApplicationStub.sh
          asset_path: ./src/universalJavaApplicationStub
          asset_content_type: text/x-shellscript

  compile:
    name: Compile the stub on ${{ matrix.os }}
    needs: draft_release # we need to know the upload URL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15 ] # macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Install shc via HomeBrew
        run: |
          brew install shc
          shc -h
      - name: Compile universalJavaApplicationStub
        run: |
          echo "Running shc..."
          shc -r -f src/universalJavaApplicationStub
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.draft_release.outputs.upload_url }}
          asset_name: universalJavaApplicationStub
          asset_path: ./src/universalJavaApplicationStub.x
          asset_content_type: application/octet-stream

  publish_release:
    name: Publish drafted release
    needs: [ draft_release, compile ]
    runs-on: ubuntu-latest
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_PERSONAL_ACCESS_TOKEN }}
        with:
          release_id: ${{ needs.draft_release.outputs.release_id }}